name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
        react-version:
          - ^19
          - ^18
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup React ${{ matrix.react-version }}
        uses: kirkeaton/setup-react@a59f1bbbcf724b8fd417e5650e7baaca553650a0 # v2.0.5
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
          react-types-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 24 }}
        name: Check formatting
        run: npm run lint
      - name: Build
        run: npm run build
      - if: ${{ matrix.node-version == 24 }}
        name: Check types
        run: npm run typecheck
      - if: ${{ matrix.node-version == 24 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@d1a4f82ae22224426628517b57eb49528d1074e1 # v2.0.5
