name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
        react-version:
          - ^19
          - ^18
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup React ${{ matrix.react-version }}
        uses: kirkeaton/setup-react@01a24bbf506c78d4f42ccc6b4102675f4ee9b4f1 # v2.0.10
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
          react-types-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 24 }}
        name: Check formatting
        run: npm run lint
      - name: Build
        run: npm run build
      - if: ${{ matrix.node-version == 24 }}
        name: Check types
        run: npm run typecheck
      - if: ${{ matrix.node-version == 24 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@31f86e6525cae7e65e285b3eae1e241cd67e8ebc # v2.0.10
